import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

const inter = Poppins({ weight: "500", subsets: ["latin"] });

export const metadata = {
  title: "Nextauth with prisma authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
